application: rpghelper-hrd
version: 2
runtime: python
api_version: 1

inbound_services:
- xmpp_message

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /images
  static_dir: images
 
- url: /stylesheets
  static_dir: stylesheets
 
- url: /admin(/.*)?
  script: rpghelper.py
  login: admin

- url: /campaigns(/.*)?
  script: campaigns.py
  
- url: /dice(/.*)?
  script: diceroller.py

- url: /chat/notify
  script: chat.py
  login: admin

- url: /chat/send_notifications
  script: chat.py
  login: admin

- url: /chat/notify_client
  script: chat.py
  login: admin

- url: /chat(/.*)?
  script: chat.py

- url: /bb_test(/.*)?
  script: bbtest.py
  login: required

- url: /map(/.*)?
  script: map.py

- url: /settings(/.*)?
  script: settings.py

- url: /_ah/xmpp/message/chat/
  script: xmpp.py

- url: /static
  static_dir: static

- url: /.*
  script: rpghelper.py
