application: rpghelper-hrd
version: 2
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: django
  version: "1.2"

inbound_services:
- xmpp_message

handlers:
- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /images
  static_dir: images
 
- url: /stylesheets
  static_dir: stylesheets
 
- url: /admin(/.*)?
  script: rpghelper.application
  login: admin

- url: /campaigns(/.*)?
  script: campaigns.application
  
- url: /dice(/.*)?
  script: diceroller.application

- url: /chat/notify
  script: chat.application
  login: admin

- url: /chat/send_notifications
  script: chat.application
  login: admin

- url: /chat/notify_client
  script: chat.application
  login: admin

- url: /chat(/.*)?
  script: chat.application

- url: /bb_test(/.*)?
  script: bbtest.application
  login: required

- url: /map(/.*)?
  script: map.application

- url: /settings(/.*)?
  script: settings.application

- url: /_ah/xmpp/message/chat/
  script: xmpp.application

- url: /static
  static_dir: static

- url: /.*
  script: rpghelper.application
